# Generated by Django 3.0.7 on 2020-12-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='password',
            field=models.DateTimeField(max_length=250, verbose_name='password'),
        ),
    ]
